apiVersion: builtin
kind: PatchTransformer
metadata:
  name: apm-java-agent
target:
  name: .*
  kind: Deployment
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: any
  spec:
    template:
      spec:
        initContainers:
          - name: dd-agent-downloader
            image: curlimages/curl
            command: ["sh", "-c", "curl -L -o /usr/share/dd-java-agent.jar $DOWNLOAD_URL"]
            env:
              - name: VERSION
                value: 0.49.0
              - name: DOWNLOAD_URL
                value: "https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.datadoghq&a=dd-java-agent&v=$(VERSION)"
            volumeMounts:
              - name: dd-java-agent
                mountPath: /usr/share
        containers:
          - name: app
            volumeMounts:
              - name: dd-java-agent
                mountPath: /usr/share/dd-java-agent.jar
                subPath: dd-java-agent.jar
        volumes:
          - name: dd-java-agent
            emptyDir: {}
